---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nodejs
spec:
  selector:
    matchLabels:
      app: example-nodejs
  template:
    metadata:
      labels:
        app: example-nodejs
    spec:
      containers:
      - name: example-nodejs
        image: test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: example-nodeejs
spec:
  selector:
    app: example-nodes
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  type: NodePort
