---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-nodejs
spec:
  selector:
    matchLabels:
      app: example-nodejs
  template:
    metadata:
      labels:
        app: example-nodejs
    spec:
      containers:
      - name: example-nodejs
        image: test
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: example-nodejs
spec:
  selector:
    app: example-nodejs
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
  type: NodePort
